### ISSUE TITLE
On Prem Version

### ISSUE THREAD

**Issue by stevesloka** [awslabs/amazon-kinesis-agent#1]
I'm looking to put the agent on a server locally in my private datacenter and stream data up to firehose. Is this supported? Also, is there a way to install without building from source?

I'm trying now and have the following error: 
```
Buildfile: /amazon-kinesis-agent/build.xml

clean:

get-java-version:

check-java-version:

init:
    [mkdir] Created dir: /amazon-kinesis-agent/ant_build

compile:
    [mkdir] Created dir: /amazon-kinesis-agent/ant_build/private
    [javac] Compiling 85 source files to /amazon-kinesis-agent/ant_build/private
    [javac] warning: Supported source version 'RELEASE_6' from annotation processor 'org.sonatype.guice.bean.scanners.index.SisuIndexAPT6' less than -source '1.7'
    [javac] /amazon-kinesis-agent/src/com/amazon/kinesis/streaming/agent/Agent.java:400: error: cannot find symbol
    [javac]         return MoreExecutors.directExecutor();
    [javac]                             ^
    [javac]   symbol:   method directExecutor()
    [javac]   location: class MoreExecutors
    [javac] 1 error
    [javac] 1 warning

BUILD FAILED
/amazon-kinesis-agent/build.xml:38: Compile failed; see the compiler error output for details.

Total time: 9 seconds
```

**Comment by chaochenq** [comment]
Hello,

You can use the setup script that's included in the package to build and install this software. What ./setup
does are:

1. download all the dependencies
2. compile and build the java code
3. set up the environment running the Kinesis Agent, including setting up init.d file, a cron job that keeps agent running, a sysconfig file to configure AWS credentials

The way you want to run the setup script is:

sudo ./setup --install
or
sudo ./setup --uninstall

For more information, see https://github.com/awslabs/amazon-kinesis-agent#installing-amazon-kinesis-agent

However the script is only tested in Red Hat and Amazon Linux. If you are running on another platform, you may want to look into changing the script to fit to your platform. Or you can build from Java code after you have downloaded all the dependencies as listed in pom.xml.

For more information, see https://github.com/awslabs/amazon-kinesis-agent#building-from-source

**Comment by stevesloka** [comment]
Thanks @chaochenq I struggled with the build a bit since I want to run the agent in a docker container. I just added a PR (#2) to let me just do a build from the setup script. Let me know your thoughts.

**Comment by chaochenq** [comment]
That's nice! I think your change makes sense and makes it easier for people to resolve the dependencies.

I will include this change in the next release.

**Comment by chaochenq** [comment]
I've included this change and updated the README file in the latest release.

Let me know if this looks good to you.

**Comment by stevesloka** [comment]
Thanks for doing this, but why not just use my PR that I setup? Was there an issue with it?

**Comment by chaochenq** [comment]
Hi, no issue with your PR at all. Thanks for doing that. I updated some more wording in the README file, and that's why I decided to make the change on my own. But the core part of setup script does the same as yours.
