### ISSUE TITLE
Init status returns the wrong exit code

### ISSUE THREAD

**Issue by ryan-b-gibson** [awslabs/amazon-kinesis-agent#10]
The init script does not return the correct exit code when checking the status of the `aws-kinesis-agent` service:
```
# service aws-kinesis-agent status
aws-kinesis-agent is stopped
# echo $?
0
```

We noticed that our puppet script was failing to start the agent because it thought the agent was already running.

**Comment by chaochenq** [comment]
Hi,

Thanks for pointing this out. It does seem to be a bug. A quick fix is to add

RETVAL=$?

after this line: https://github.com/awslabs/amazon-kinesis-agent/blob/master/bin/aws-kinesis-agent#L150

**Comment by chaochenq** [comment]
Fixed in the latest release
