### ISSUE TITLE
Unable to parse date as timestamp in Elasticsearch

### ISSUE THREAD

**Issue by sdole** [awslabs/amazon-kinesis-agent#108]
I have aws-kinesis-agent pushing logs to firehose and then on to elasticsearch. I am able to see records in ES just fine, however, the log event timestamp field is not being indexed in ES as a timestamp - instead is being indexed as a String. Is there anything I can do at the agent level so that log event timestamp goes in as timestamp in ES?

**Comment by PeterGolledge** [comment]
I'm getting the same result, it seems that the agent is not converting syslog dates into the  iso8601 format so they don't get loaded as type date.  This means you can't create a date histogram etc in Kibana.

**Comment by sdole** [comment]
help!

**Comment by buholzer** [comment]
Same issue, what is the intended functionality? Should the agent convert or ES on create?

**Comment by hlorofos** [comment]
Use ES mapping for this. Setup mapping (https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html) for your date/time variable like this:

"mappings": {
      "type1": {
        "_source": {
          "enabled": false
        },
        "properties": {
          "datetime": {
            "format": "YYYY-MM-dd HH:mm:ss",
            "type": "date"
          }
        }
      }
    },

**Comment by sdole** [comment]
So, I fixed my issue by adding an index template so that whenever a new index with a named prefix is created, it gets the mapping associated with the type I had previously defined in the kinesis firehose configuration. In my kinesis firehose configuration, my stream is configured to deliver to ES with a mapping type of applogs_type. So, my PUT template request looked like this:

`PUT _template/applogs_type_template
{
    "template" : "applogs-*",
    
    "mappings" : {
        "applogs_type" : {
            "properties":{
                "timestamp":{
                    "type":"date",
                    "format":"dd/MMM/YYYY HH:mm:ss,SSS"
                }
            }
        }
    }
}`

**Comment by nitheesh121** [comment]
i have come across the same issue , @sdole , where you have added this index template ? I am not seeing any place where we can add this in the kinesis firehose

**Comment by khushnaseeb** [comment]
@sdole  you saved my day! Thanks a lot for the template solution.
