### ISSUE TITLE
Missing error messages

### ISSUE THREAD

**Issue by Schadix** [awslabs/amazon-kinesis-agent#12]
I deployed through 'sudo yum install –y aws-kinesis-agent' on 2015/09 Amazon AMI.
Initially the aws-kinesis-agent-user did not have access to my file(s) configured, but no error message was thrown or information that the agent did not have access. I would expect an error message in the log that the path is not accessible for the agent.

After giving access to the file everything worked fine.

Then I configured a non-existing stream (Kinesis configuration).
Again no error message in the log file about the stream endpoint. Instead the message that 0 records had been send to the destination (which is correct, but not obvious due to the stream not existing).
I would expect an error message that the stream does not exist.

**Comment by chaochenq** [comment]
Thanks for reporting this. 

In the first case where the aws-kinesis-agent-user didn't have access to the file. Could you tell me which permission the aws-kinesis-agent-user was lacking? We require to grant read permission on files and execution permission on the directory holding the files. In the cases where these permissions are missing, the agent should fail to be started up with IOException thrown:

FATAL: Thread FileTailer[fh:stream:filePath] threw an unrecoverable error. Aborting application
java.lang.RuntimeException: java.nio.file.AccessDeniedException: filePath
        at com.google.common.base.Throwables.propagate(Unknown Source)
        at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(Unknown Source)
        at com.google.common.util.concurrent.Callables$3.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.file.AccessDeniedException: filePath
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
        at java.nio.channels.FileChannel.open(FileChannel.java:287)
        at java.nio.channels.FileChannel.open(FileChannel.java:334)
        at com.amazon.kinesis.streaming.agent.tailing.TrackedFile.open(Unknown Source)
        at com.amazon.kinesis.streaming.agent.tailing.SourceFileTracker.initialize(Unknown Source)
        at com.amazon.kinesis.streaming.agent.tailing.FileTailer.initialize(Unknown Source)
        at com.amazon.kinesis.streaming.agent.tailing.FileTailer.startUp(Unknown Source)
        ... 3 more

Interestingly that you were able to start the agent without giving the agent user access to the files...

In the second case where you configured a non-existing stream, you should be able to see the ResourceNotFound exception if you add "log.level": "DEBUG" to the agent's config file. We might need to move this error message to ERROR level though.

**Comment by Schadix** [comment]
Hi Chaochen, the agent didn't have any access to logfile. Neither read nor execution. The path was to my user directory for testing and the aws-kinesis-agent-user didn't have any access rights to that.

I'll check the log.level: DEBUG

**Comment by Schadix** [comment]
Interesting. I tested a little more. Assuming this path
/home/ec2-user/myapp/log/output.log

When the /home/ec2-user or /home/ec2-user/myapp folder is missing the execution flag (go-x), there is no error message to stdout and the service starts and no error logging in /var/log/aws-kinesis-agent.
As soon as the execution flag is set down to /home/ec2-user/myapp, the error message appears when trying to launch the service and in the start-aws-kinesis-agent.initlog.

I would think ERROR logging for ResourceNotFound exception is appropriate, given that the agent is not working as expected and an alarm should notify the user/system about that fact (trigger action).

**Comment by chaochenq** [comment]
Interesting... Could you elaborate on "As soon as the execution flag is set down to /home/ec2-user/myapp, the error message appears"?

what's the current permission set to /home/ec2-user/, /home/ec2-user/myapp/, /home/ec2-user/myapp/log/, and /home/ec2-user/myapp/log/output.log?

I noticed that when data is put and stored in ec2-user directory, there exists some unexpected behavior (no error message to stdout nor log file). But I haven't been able to find a setting that could fail the launch (which is the correct behavior).

But if you move your data to some other directory like /data/, it'll work more friendly

**Comment by chaochenq** [comment]
At the same time, could you also try changing this message from "debug" to "error" to see if it helps?

https://github.com/awslabs/amazon-kinesis-agent/blob/master/src/com/amazon/kinesis/streaming/agent/tailing/SimplePublisher.java#L206

I'm patching another release to fix the error message too.

**Comment by chaochenq** [comment]
I've pushed a patch to switch some of the error messages from DEBUG to ERROR.
