### ISSUE TITLE
Log rotation makes agent go crazy

### ISSUE THREAD

**Issue by thesmart** [awslabs/amazon-kinesis-agent#14]
I setup the agent to feed from a log file that gets rotated by a service (a producer) automatically.  When the rotation occurs, the kinesis agent freaks out and spews a stack trace every 100ms!  I totally understand why the agent would get confused, and I have disabled the automatic rotation assuming the agent does this for me automatically.  However, spewing a stack trace to disk every 100ms is probably not a good idea as it might fill up a disk or introduce unnecessary IO load.

Might it make sense to have the process die when it encounters this condition?  Most production environments have their process monitoring, and its a best practice to have a process die with a good error message when it is in a non-recoverable state.  I'd much prefer that to thrashing.

Here is what it spews, every 100ms or so:

```2016-03-30 16:59:42.869+0000 ip-172-30-10-195 (FileTailer[kinesis:events:/var/log/events.log]) com.amazon.kinesis.streaming.agent.tailing.FileTailer [ERROR] FileTailer[kinesis:events:/var/log/events.log]: Error when processing current input file or when tracking its status.
java.lang.IllegalStateException
        at com.google.common.base.Preconditions.checkState(Preconditions.java:158)
        at com.amazon.kinesis.streaming.agent.tailing.TrackedFileRotationAnalyzer.findCurrentOpenFileAfterTruncate(Unknown Source)
        at com.amazon.kinesis.streaming.agent.tailing.SourceFileTracker.updateCurrentFile(Unknown Source)
        at com.amazon.kinesis.streaming.agent.tailing.SourceFileTracker.refresh(Unknown Source)
        at com.amazon.kinesis.streaming.agent.tailing.FileTailer.updateRecordParser(Unknown Source)
        at com.amazon.kinesis.streaming.agent.tailing.FileTailer.processRecords(Unknown Source)
        at com.amazon.kinesis.streaming.agent.tailing.FileTailer.runOnce(Unknown Source)
        at com.amazon.kinesis.streaming.agent.tailing.FileTailer.run(Unknown Source)
        at com.google.common.util.concurrent.AbstractExecutionThreadService$1$2.run(AbstractExecutionThreadService.java:60)
        at com.google.common.util.concurrent.Callables$3.run(Callables.java:95)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by chaochenq** [comment]
Hello, can I take a look at your config? How often did your files get rotated? And what's your rotation rule?

The Agent doesn't rotate the files. By saying "handling file rotations" we meant that Agent should be able to read records from your rotated files to catch up or recover from failures. 

There are some limitations though, on the rotation rules that you want to apply to your tailed files. For example, Agent is not currently able to read and parse compressed files. Also monitored files are limited to a minimum interval of 1 second for rotation or creation. The fact that Agent is throwing out errors every 100ms is that this is the default time interval it uses to poll the latest modified file matching filePattern, and this can be configured by setting minTimeBetweenFilePollsMillis in your flow configuration. 

What happens in your case is that, when Agent tried to tail the new data (every 100ms), it first tried to find the latest modified file matching the filePattern. There are some existing known issues that could occur depending on the rotation mode. For example, if you use copytruncate, the state could unfortunately be in a mess when Agent tried to find the file to track and tail. Could you try other rotation mode (i.e. rename/truncate/create/copy)?

**Comment by thesmart** [comment]
Hey sorry for the late reply.  I believe this was caused by me editing the file rather than logrotate.  Closing.

**Comment by Schodemeiss** [comment]
I'm actually having the same problem (see https://github.com/awslabs/amazon-kinesis-agent/issues/50).

Did you manage to resolve this? Was it definitely you editing the file rather than logrotate? Can you send me your logrotate setup?

**Comment by abrudin** [comment]
This affects me too. We can work around the problem by using another rotation mode, but it still seems like a bug that the agent spews stacktraces every 100 ms, it would be better if it just died, so one wouldn't have to worry that the disk fills up.

**Comment by test1432** [comment]
Hi I'm trying to add tags to get all logs in one stretch but could'nt able to figure out how to configure kinesis agent for data streaming  and log rotation to kinesis stream with sys logs,kern logs,apache logs etc.......
Could anyone help me in adding the tags to kinesis agent
