### ISSUE TITLE
Unit Tests

### ISSUE THREAD

**Issue by wslulciuc** [awslabs/amazon-kinesis-agent#16]
I'm currently exploring the possibility of using this agent, but noticed proper code coverage is absent and can only assume the tests are in a separate project? If not, I'd be more than willing to help out with getting unit tests written!

**Comment by chaochenq** [comment]
We haven't released the testing code but will do that along with our next coming release on 4/11. Thanks!

**Comment by wslulciuc** [comment]
Awesome! Looking forward to seeing the improvements in the next release.
