### ISSUE TITLE
Updated to 1.1 no longer works

### ISSUE THREAD

**Issue by mattford63** [awslabs/amazon-kinesis-agent#18]
Hi,

Updated our working agent from 1.0 to 1.1 and uploads to kinesis streams no longer seem to work.

We are using instance roles to allow access to kinesis resources.  

Parsing is successful but no messages ever seem to be sent.  What's more in the configuration file if we set a completely bogus stream name then no errors are reported everything happily continues without error (but obviously still not uploading anything).

**Comment by chaochenq** [comment]
Hello, could you turn on DEBUG in the log and grep for potential stack trace or error message?

You can change the log level by adding

"log.level": "TRACE" or "log.level": "DEBUG" to the top of the config file.

If you think the log is too noisy, could you send it to me at chaocheq@amazon.com? I'll take a look and let you know ASAP.

Right now the error message of each record is put in TRACE level, that's probably the reason why you didn't see the error in ERROR. We probably shouldn't have done that way, but this intent to make the ERROR cleaner.

**Comment by chaochenq** [comment]
At the same time, could you also try changing this message from "debug" to "error" to see if it helps?

https://github.com/awslabs/amazon-kinesis-agent/blob/master/src/com/amazon/kinesis/streaming/agent/tailing/SimplePublisher.java#L206

I'm patching another release to fix the error message too.

**Comment by mattford63** [comment]
With debug level monitoring I see this:

```2016-04-13 07:34:50.021+0000 ip-10-30-156-195 (sender-7) com.amazon.kinesis.streaming.agent.tailing.AsyncPublisher [DEBUG] AsyncPublish
er[kinesis:dev-amazon-agent-kinesis-AmazonAgentKinesisStream-2EHGD272A811:/var/log/canary/ingress/ingress.log]:RecordBuffer(id=11,recor
ds=500,bytes=252824) Retriable send error (com.amazonaws.AmazonClientException: Unable to marshall request to JSON: com/fasterxml/jacks
on/dataformat/cbor/CBORFactory). Will retry.  ```

**Comment by mattford63** [comment]
Found a similar error here

http://stackoverflow.com/questions/35467833/unable-to-marshall-request-to-json-amazon-aws

**Comment by mattford63** [comment]
I've been able to get the agent working by downgrading the Amazon SDK to the version used in 1.0.

**Comment by mattford63** [comment]
```
Date:   Wed Apr 13 10:10:53 2016 +0000

    Downgrade SDK

diff --git a/pom.xml b/pom.xml
index 219c7de..1d9d638 100644
--- a/pom.xml
+++ b/pom.xml
@@ -23,7 +23,7 @@
     </licenses>
 
     <properties>
-        <aws-java-sdk.version>1.10.67</aws-java-sdk.version>
+        <aws-java-sdk.version>1.10.26</aws-java-sdk.version>
     </properties>
 
     <dependencies>
@@ -209,4 +209,4 @@
       </plugins>
     </build>
 
-</project>
\ No newline at end of file
+</project>
diff --git a/setup b/setup
index 9d4f3f6..57fc582 100755
--- a/setup
+++ b/setup
@@ -47,7 +47,7 @@ download_dependencies() {
   install -d ${dependencies_dir}
   
   echo "Downloading dependencies ..."
-  aws_java_sdk_version="1.10.67"
+  aws_java_sdk_version="1.10.26"
   
   remote_mvn_pkg="com.amazonaws:aws-java-sdk-core:${aws_java_sdk_version} \
                   com.amazonaws:aws-java-sdk-kinesis:${aws_java_sdk_version} \```

**Comment by chaochenq** [comment]
Sorry for the inconvenience. I'm gonna downgrade the sdk version then

**Comment by chaochenq** [comment]
I've pushed a patch release.
