### ISSUE TITLE
CSVTOJSON preprocessing option not transforming csv file to json

### ISSUE THREAD

**Issue by deepthinalla92** [awslabs/amazon-kinesis-agent#182]
Hi,
I am trying to convert a csv file to json using kinesis agent before sending it to a deliverystream. Here is my agent.json file

{
  "cloudwatch.emitMetrics": true,
  "kinesis.endpoint": "",
  "firehose.endpoint": "https://firehose.us-west-2.amazonaws.com",

  "flows": [
{
      "filePattern": "/tmp/logs/syslog1.log",
      "deliveryStream": "test-cas-logs",
      "multiLineStartPattern": "([0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])T([0-1][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])-)",
      "initialPosition": "START_OF_FILE",
      "log.level" : "DEBUG"
},
    {
      "filePattern": "/tmp/logs/syslog1.log",
      "deliveryStream": "test-firewall-logs-to-ES",
      "initialPosition": "START_OF_FILE",
      "multiLineStartPattern": "([0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1])T([0-1][0-9]|2[0-3]):([0-5][0-9]):([0-5][0-9])-)",
      "log.level": "DEBUG",
      "optionName": "CSVTOJSON",
      "customFieldNames": [ "futureuse", "timestamp", "id", "content" , "type" ],
      "delimiter": ","
 }
  ]
}

Trying to convert the logs to json when sending logs to "test-firewall-logs-to-ES" delivery stream. I see that non transformed data is being sent to delivery stream

here are the sample logs that i am trying to convert to JSON.

2019-03-19T13:02:41-07:00 1,2019/03/19 13:02:41,0019001723,TRAFFIC,drop
2019-03-19T13:02:41-07:00 1,2019/03/19 13:02:41,0019001723,TRAFFIC,drop
2019-03-19T13:02:41-07:00 1,2019/03/19 13:02:41,0019001723,TRAFFIC,drop
2019-03-19T13:02:41-07:00 1,2019/03/19 13:02:41,0019001723,TRAFFIC,drop

Could someone help me figure out the issue

**Comment by deepthinalla92** [comment]
dataProcessingOptions attribute is missing in my code

**Comment by parlad** [comment]
`"dataProcessingOptions": [
         {
            "optionName": "CSVTOJSON",
            "customFieldNames": ["colname", "colname", "colname","colname", "colname"]
         }`


Should work
