### ISSUE TITLE
What are the cloudwatch permissions required?

### ISSUE THREAD

**Issue by mattford63** [awslabs/amazon-kinesis-agent#19]
I'd like to use instance roles to give access to the cloudwatch to report metrics.  Do you have a minimal policy?

**Comment by chaochenq** [comment]
Hello, the only operation that you should allow for emitting CloudWatch metrics is: **PutMetricData**

You can also take a look at the section "AWS Credentials"
http://docs.aws.amazon.com/firehose/latest/dev/writing-with-agents.html#setting-up-agent

**Comment by mattford63** [comment]
Added that permission and everything started to work.
