### ISSUE TITLE
Cannot compile the latest build

### ISSUE THREAD

**Issue by tarunsas** [awslabs/amazon-kinesis-agent#21]
when i try mvn clean install or ./setup --install

init:
    [mkdir] Created dir: /home/parallels/software/amazon-kinesis-agent-master/ant_build

compile:
    [mkdir] Created dir: /home/parallels/software/amazon-kinesis-agent-master/ant_build/private
    [javac] Compiling 102 source files to /home/parallels/software/amazon-kinesis-agent-master/ant_build/private
    [javac] warning: [options] bootstrap class path not set in conjunction with -source 1.7
    [javac] warning: Supported source version 'RELEASE_6' from annotation processor 'org.sonatype.guice.bean.scanners.index.SisuIndexAPT6' less than -source '1.7'
    [javac] /home/parallels/software/amazon-kinesis-agent-master/src/com/amazon/kinesis/streaming/agent/Agent.java:400: error: cannot find symbol
    [javac]         return MoreExecutors.directExecutor();
    [javac]                             ^
    [javac]   symbol:   method directExecutor()
    [javac]   location: class MoreExecutors
    [javac] /home/parallels/software/amazon-kinesis-agent-master/src/com/amazon/kinesis/streaming/agent/config/Configuration.java:125: error: cannot find symbol
    [javac]                 Doubles.stringConverter());
    [javac]                        ^
    [javac]   symbol:   method stringConverter()
    [javac]   location: class Doubles
    [javac] /home/parallels/software/amazon-kinesis-agent-master/src/com/amazon/kinesis/streaming/agent/config/Configuration.java:128: error: cannot find symbol
    [javac]                 Ints.stringConverter());
    [javac]                     ^
    [javac]   symbol:   method stringConverter()
    [javac]   location: class Ints
    [javac] /home/parallels/software/amazon-kinesis-agent-master/src/com/amazon/kinesis/streaming/agent/config/Configuration.java:131: error: cannot find symbol
    [javac]                 Longs.stringConverter());
    [javac]                      ^
    [javac]   symbol:   method stringConverter()
    [javac]   location: class Longs
    [javac] Note: /home/parallels/software/amazon-kinesis-agent-master/src/com/amazon/kinesis/streaming/agent/tailing/FileFlow.java uses unchecked or unsafe operations.
    [javac] Note: Recompile with -Xlint:unchecked for details.
    [javac] 4 errors
    [javac] 1 warning

BUILD FAILED
/home/parallels/software/amazon-kinesis-agent-master/build.xml:38: Compile failed; see the compiler error output for details.

Can someone please look at it.?

**Comment by chaochenq** [comment]
What jdk version are you using? It requires jdk 1.7 or above to build the project.

**Comment by tarunsas** [comment]
We are using 1.8

**Comment by chaochenq** [comment]
I don't seem to be able to reproduce this on my machine... I wonder if it's because you have conflicts in your java classpath. Could you check the jar files under these two directories to see if there are conflicts?

https://github.com/awslabs/amazon-kinesis-agent/blob/master/build.xml#L15-L18

For example, looking at your error message, we use Doubles.stringConverter() from http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/primitives/Doubles.html, if you have other dependencies under /usr/share/java that includes another Doubles, then it might cause errors.

**Comment by Paul424** [comment]
I experienced the same issue running ubuntu 14.04; i guess Ubuntu is not supported?

**Comment by diranged** [comment]
So I  have a PR opened to add Ubuntu support -- and I thought I had it all nailed down, when suddenly I started getting this error. I have blown away my vagrant dev environment and am working to reproduce the error. Will report back when I have something useful.

**Comment by diranged** [comment]
@chaochenq, Hey I think I have the fix... I'll submit a PR:

```
commit 3df0fd1f9538d7b890e042c7bfede3ccab135dab
Author: Matt Wise <matt@nextdoor.com>
Date:   Thu Apr 28 13:21:34 2016 -0700

    Re-order the build dependency search path.
    
    By passing in the build dependency search path with the system path
    first, if the system already has a library (like guava) installed thats
    older than the desired library, it is then loaded up during the build
    process and the downloaded dependency is ignored.

diff --git a/build.xml b/build.xml
index 35de60e..67c5e0b 100644
--- a/build.xml
+++ b/build.xml
@@ -13,8 +13,8 @@
     <property name="build.dependencies" location="dependencies" />
 
     <path id="classpath">
-        <fileset dir="/usr/share/java" includes="**/*.jar" />
         <fileset dir="${build.dependencies}" includes="**/*.jar" />
+        <fileset dir="/usr/share/java" includes="**/*.jar" />
     </path>
 
     <target name="get-java-version">
@@ -57,4 +57,4 @@
 
     <target name="release" depends="clean, compile, build" />
```

**Comment by diranged** [comment]
I believe https://github.com/awslabs/amazon-kinesis-agent/pull/27 fixes this

**Comment by Paul424** [comment]
I made some progress (the rough way...) I managed to create a runnable jar using intellij using the pom file. Notice that it requires the custom.log4j.xml to be added to the jar at the same location as the Logging class. (this only took me about an hour to understand and solve...).
Paul

**Comment by diranged** [comment]
@Paul424 in an ideal world, we'd find a way to bundle all the required JARs together into a single massive JAR with all of the dependencies in it. I'm not familiar enough with Java to know how to do this in the build step, but it would massively reduce the complexity of the package I think.

Of course, this whole thing could move into a docker container too, which is on my ToDo list.
