### ISSUE TITLE
Syslog to JSON

### ISSUE THREAD

**Issue by mattford63** [awslabs/amazon-kinesis-agent#23]
Hi,

We had the latest version of the agent working - converting syslog records to json and uploading to kinesis.  And then it just stopped.  Redeployed and the same thing.  At a complete loss why.  The error and trace logging shows nothing.  New logs are reported as parsed but nothing ever gets uploaded.  The upload count just sits at zero.

I setup another configuration entry with CSVTOJSON configured and some dummy data.   This works fine, logs are parsed, converted to JSON and uploaded.

Sorry this bug report is so poor :-(

Any pointers on what your steps to debug would be much appreciated.  I see there are some tests - how are these run?  Are you testing direct against Kinesis (we are) or do you have a mock kinesis setup you could share?

**Comment by mattford63** [comment]
We think we've found the issue - to do with Syslog formats.  We are using high precision dates.

**Comment by mattford63** [comment]
All though it doesn't explain why we don't see any log parsing exceptions.

**Comment by mattford63** [comment]
I made a PR to fix up my logging.

**Comment by chaochenq** [comment]
Thanks for reporting this and providing a fix. I'll take a look and merge it.

**Comment by chaochenq** [comment]
I've merged the PR. Meanwhile I'll try to improve the logging and add an ant target to run the test suites.
