### ISSUE TITLE
 openjdk-11-jdk support

### ISSUE THREAD

**Issue by NothinRandom** [awslabs/amazon-kinesis-agent#252]
Could the team provide an ETA on when openjdk-11-jdk would be integrated?  It been out for quite a while now.  I know openjdk-8-jdk has support until 2026, but this means any system that leverages this agent must rely on the the older version; thus, requiring another version of java runtime.  It would be great if we can migrate to v11 so that systems don't need a separate runtime version just to operate this agent.  Thanks!

**Comment by pg-faheem** [comment]
OpenJDK 11 Support - https://github.com/awslabs/amazon-kinesis-agent/pull/262

**Comment by NothinRandom** [comment]
Thanks for the update!
