### ISSUE TITLE
Exceeded max record size: 40960

### ISSUE THREAD

**Issue by ulsa** [awslabs/amazon-kinesis-agent#35]
I have records that usually are around 20 KB, but can sometimes be larger. I'm occasionally running into what seems like a hardcoded limit of 40 KB (40960 B):

```
2016-06-16 13:25:23.474+0000 ip-172-31-22-141 (FileTailer[fh:myfirehose:/data/transactions.log])
 com.amazon.kinesis.streaming.agent.tailing.FileTailer [WARN] FileTailer[fh:myfirehose:/data/transactions.log]:
 Truncated a record in TrackedFile(id=(dev=ca10,ino=12), path=/data/transactions.log,
 lastModifiedTime=1466083520220, size=22411), because it exceeded the the configured max record size: 40960
```

There are a number of classes that have this limit set:

* [FirehoseFileFlow](https://github.com/awslabs/amazon-kinesis-agent/blob/master/src/com/amazon/kinesis/streaming/agent/tailing/FirehoseFileFlow.java)
* [FirehoseRecord](https://github.com/awslabs/amazon-kinesis-agent/blob/master/src/com/amazon/kinesis/streaming/agent/tailing/FirehoseRecord.java)
* [FirehoseParser](https://github.com/awslabs/amazon-kinesis-agent/blob/master/src/com/amazon/kinesis/streaming/agent/tailing/FirehoseParser.java)

Any suggestions on how this can be overridden, or do I have to build my own binary?

**Comment by ulsa** [comment]
I ended up removing the yum package, cloning this repo, changing the constant to near 1MB, and then running:

```
sudo ./setup --install
```

That worked fine.

**Comment by chaochenq** [comment]
Hi @ulsa thank you for reporting this. The maximum size limit was set in Agent before we increased the size limit of our Firehose backend service. I'll roll out the change in the next release to yum package.

You are doing the right thing, could you submit a PR since you already have tested the change? Thank you!

**Comment by ulsa** [comment]
It's a one-liner. Here's the diff:

```
diff --git a/src/com/amazon/kinesis/streaming/agent/tailing/FirehoseConstants.java b/src/com/amazon/kinesis/streaming/agent/tailing/FirehoseConstants.java
index 66dae71..d03a7e3 100644
--- a/src/com/amazon/kinesis/streaming/agent/tailing/FirehoseConstants.java
+++ b/src/com/amazon/kinesis/streaming/agent/tailing/FirehoseConstants.java
@@ -19,7 +19,7 @@ public final class FirehoseConstants extends Constants {
     public static final String DESTINATION_KEY = "deliveryStream";
     
     public static final int PER_RECORD_OVERHEAD_BYTES = 0;
-    public static final int MAX_RECORD_SIZE_BYTES = 40_960;
+    public static final int MAX_RECORD_SIZE_BYTES = 999_424; // 976K
     public static final int PER_BUFFER_OVERHEAD_BYTES = 0;
     public static final int MAX_BATCH_PUT_SIZE_RECORDS = 500;
     public static final int MAX_BATCH_PUT_SIZE_BYTES = 4 * 1024 * 1024;
```

**Comment by chaochenq** [comment]
Thanks @ulsa, I've made the change to bump the limit to 1000KB. Will roll out the change in the next release.
