### ISSUE TITLE
Support EC2 metadata service for keys

### ISSUE THREAD

**Issue by mleventi** [awslabs/amazon-kinesis-agent#4]
The agent should fallback to using the metadata service if no keys are passed in as env variables.

**Comment by chaochenq** [comment]
Hello, the agent falls back to use InstanceProfileCredentialsProvider at the bottom of the chain:

https://github.com/awslabs/amazon-kinesis-agent/blob/master/src/com/amazon/kinesis/streaming/agent/AgentAWSCredentialsProviderChain.java

If you have an EC2 instance launched with an IAM role, the agent will retrieve the keys stored in the instance metadata if you don't specify keys in other places.

Did you run into any issues on that?
