### ISSUE TITLE
Customize the log4j logger...

### ISSUE THREAD

**Issue by diranged** [awslabs/amazon-kinesis-agent#42]
Since you're leveraging log4j, we should be able to set our own log4j config file and customize our logging as we wish. Is that possible now, or are there code changes required to support that?

**Comment by chaochenq** [comment]
We have these agent configuration options available:

log.level - update agent log level. Defaut is INFO
log.file - specify log path (default is /var/log/aws-kinesis-agent)
log.maxBackupIndex - The maximum number of backup log files to keep. Default is 5.
log.maxFileSize - The maximum allowed log file size (in bytes) before rolling over. Default is 10MB

If you want to edit the log4j config without editing agent config file, you can directly edit in the XML file:
https://github.com/awslabs/amazon-kinesis-agent/blob/master/src/com/amazon/kinesis/streaming/agent/custom.log4j.xml
