### ISSUE TITLE
Kinesis Agent CloudWatch metrics should be tagged with the host ID..

### ISSUE THREAD

**Issue by diranged** [awslabs/amazon-kinesis-agent#46]
The Kinesis Agent should try to tag the metrics with the instance ID (if the metadata service is available) -- so that we can more easily track down which hosts are behaving differently than others.

**Comment by chaochenq** [comment]
This is a good point, I've noted it down. Thanks

**Comment by chaochenq** [comment]
@diranged FYI I have implemented this but waiting for another team to release the aws-kinesis-agent package into Amazon AMI. After that's done I'm going to push the code to Github. Sorry for keeping this late!

**Comment by chaochenq** [comment]
This is merged with the latest release
