### ISSUE TITLE
Race condition inside aws-kinesis-agent-babysit

### ISSUE THREAD

**Issue by chris-gilmore** [awslabs/amazon-kinesis-agent#47]
Occasionally I will get a `FAILURE` when restarting `aws-kinesis-agent` (for example, inside an `ansible playbook run`).  I've tracked it down to the `babysit cron job` attempting to also restart while another restart is in progress.  During the stopping phase of my restart, there is a short period of time in which the `PIDFILE` still exists but the agent has been killed.  If this happens at the top of a minute (during which the `babysit cron job` runs), then the `babysit cron job` will think the agent has unexpectedly died.  See here for the relevant code inside the `babysit cron job`:
```bash
# Check if PID file exists. 
# If it does not, it means either the agent was never started or it was stopped by the user.
[[ -f $PIDFILE ]] || exit 0

# Check if the child Java process is alive. If not, we should start
[[ -n $(get_agent_pid) ]] || start_agent
```
I propose adding a `sleep` in between the above two statements, for example:
```bash
[[ -f $PIDFILE ]] || exit 0
sleep 12
[[ -n $(get_agent_pid) ]] || start_agent
```
Sleeping for 1 or 2 seconds is probably enough, but I'd feel safer with a little more insurance of 12 seconds.
See the following note inside the `SysVinit script` for the agent:
````
SHUTDOWN_TIME=11   #10 second default value in AgentConfiguration.java, +1 second buffer 
```

**Comment by chaochenq** [comment]
This is a good point. Thanks for diving deep into this!

Probably 12 is not even safe enough, because we want the babysit to think that $(get_agent_pid) is not empty, that requires a wait for a full stop + start, in worst case Shutdown can take 11 seconds, but the start could also take sometime, what do you think?

**Comment by chris-gilmore** [comment]
After thinking more about this, I now realize that sleeping for any amount of time will not solve the underlying issue -- it just merely pushes ahead the time in which a race condition may still exist.  For example, imagine if my restart were to occur 12 seconds after the `babysit` started, then we're back to the same situation.
I think I need to noodle on this some more ...
What do you think about maybe having the `babysit` make a `status` call to the agent's `SysVinit script`, with the `do_status` function wrapped around the same `MUTEXFILE` as the `do_start()` and `do_stop()` functions?
And then the `babysit` script can look more like the `awslogs-nanny` script (reproduced below):
```
#!/bin/sh
# Version: 1.1.2-rpm

# This script will restart the awslogs service if it has died

service awslogs status >/dev/null
status=$?

if [ "$status" -eq "1" -o "$status" -eq "2" ]; then
    service awslogs restart
fi
```

**Comment by chris-gilmore** [comment]
After some more testing, I believe even the real underlying issue is mutex-resistant, since the daemonizing of `start-aws-kinesis-agent` is continued into the background outside of the mutexed region.
If another process then enters the `do_stop()` while the initialization of `start-aws-kinesis-agent` is still in progress, then a potential core dump is possible.  See for example this real world error from `/tmp/aws-kinesis-agent.*.initlog`
```
Terminated (core dumped)
awk: (FILENAME=- FNR=3) warning: error writing standard output (Broken pipe)
```
However, if we can wrap the `do_status` call with the same `MUTEXFILE`, then we can at least prevent the `babysit` from falsely assuming the agent has unexpectedly died, and thus preventing a double restart of the agent.
I've submitted a pull request that wraps all the commands inside a mutex region, and closes the file descriptor (200) so as not to be inherited by the daemon.

**Comment by chaochenq** [comment]
Thanks @chris-gilmore for looking deep into this, I appreciate it. I will take a look at this next week :)

**Comment by chaochenq** [comment]
Actually I don't remember any specific reason why I put the conditions separately, how about we simply check the PID file and process at the same time? That would reduce the chance for a race condition too

if [ -f $PIDFILE ] && [ -z $(get_agent_pid) ]; then
  start_agent
fi

exit 0

What do you think?

**Comment by chris-gilmore** [comment]
I tested your proposal and confirmed that it does not help alleviate the problem.

The issue is with running the `babysit check` while another process is in the middle of running the `do_stop()` from the `sysvinit script`.  There is a small but perceptible amount of time within the `do_stop()` in which the `agent_pid` has been killed while the `PIDFILE` has not yet been deleted.  Therefore, we wish to prevent the `babysit check` from running simultaneously as the `do_stop()`.

**Comment by chaochenq** [comment]
Makes sense. I'll test it out and merge the PR. Thanks!

**Comment by chaochenq** [comment]
Makes sense. I'll test it out and merge the PR. Thanks!

**Comment by chaochenq** [comment]
Makes sense. I'll test it out and merge the PR. Thanks!
