### ISSUE TITLE
SingleLineSplitter is expensive

### ISSUE THREAD

**Issue by mleventi** [awslabs/amazon-kinesis-agent#5]
Hello,

I am a bit concerned that the default behavior for this project (which itself is the default behavior for Firehose) can be extremely costly with regards to the 5k minimum record size. Naive usage means a record per newline which for us is around 300 bytes. It would be excellent to have a multi-line splitter which makes better packing of many lines into a single record. That way we aren't wasting 95% of the bandwidth reaching the record minimum.

-Matt

**Comment by chaochenq** [comment]
Hello,

Have you checked out RegexSplitter (https://github.com/awslabs/amazon-kinesis-agent/blob/master/src/com/amazon/kinesis/streaming/agent/tailing/RegexSplitter.java)?

This is the multi-line splitter that we offer to parse by delimiters. You can specify a "multiLineStartPattern" which is a regular expression by which we parse records. As long as the start of a line matches this pattern, the agent will consider the lines after this pattern as a single records until it reaches another pattern. For more details, please refer to:

http://docs.aws.amazon.com/firehose/latest/dev/writing-with-agents.html#agent-config-settings

Thanks!

**Comment by alexjimenezes** [comment]
> Hello,
> 
> Have you checked out RegexSplitter (https://github.com/awslabs/amazon-kinesis-agent/blob/master/src/com/amazon/kinesis/streaming/agent/tailing/RegexSplitter.java)?
> 
> This is the multi-line splitter that we offer to parse by delimiters. You can specify a "multiLineStartPattern" which is a regular expression by which we parse records. As long as the start of a line matches this pattern, the agent will consider the lines after this pattern as a single records until it reaches another pattern. For more details, please refer to:
> 
> http://docs.aws.amazon.com/firehose/latest/dev/writing-with-agents.html#agent-config-settings
> 
> Thanks!

Hi!

I have a question about this. Say I am parsing a log that has information about the same "object" in multiple continuos lines. The separator would be `END\n^.*>> INIT` where `END` is the end of a line and the the next lines has some text until `>> INIT`. Would the multiline splitter be able to use this to put all the lines in between in one log? Or does the regular expression have to be in just one line?

Regards,

Alex
