### ISSUE TITLE
agent sends duplicate events when monitoring 2+ files on ubuntu

### ISSUE THREAD

**Issue by jpilon** [awslabs/amazon-kinesis-agent#70]
Hello,

Has anyone noticed / reported duplicates being sent through kinesis? I have a node app that writes events to a file that the agent monitors, it works great when it's just one file. When I enable clustering (node.js) and have the app run on 2 cores and each worker writes to it's own log file, that's when duplicates start showing up in firehose. I compared the events from the raw log file to the GZ file firehose writes to S3 and the raw log is correct with the S3 version having duplicates.

This is happening on Ubuntu 16.04.1

Anyone experienced anything similar? I'm at a loss for what the problem might be.

Kinesis config:
`
{
  "checkpointFile": "/path/to/kinesis/run/checkpoints",
  "awsAccessKeyId": "",
  "awsSecretAccessKey": "",
  "cloudwatch.emitMetrics": true,
  "firehose.endpoint": "firehose.us-east-1.amazonaws.com",

  "flows": [
    {
      "filePattern": "/home/app/logs/raw/*.log",
      "deliveryStream": "name"
    }
  ]
}
`

**Comment by jpilon** [comment]
Looks like there is a possibility of duplicate records due to the agent retry submission of batches. I assumed the agent would know whether or not a batch was sent successfully to avoid these kinds of duplicates but I suppose not, and didn't see anything in the doc's about this with the agent. No big deal, data is imported to a temp table in redshift and a duplicate query is run to weed them out. All good!

**Comment by chaochenq** [comment]
Hi, the cause of the duplicate might come from the Kinesis end too. For example, when networking is in unhealthy condition and Kinesis Agent sends the records to Kinesis Streams or Kinesis Firehose by calling PutRecords or PutRecordBatch, and API might timeout on the Agent client side but ended up succeeding on the server side. In this case Agent won't know whether or not the put succeeds, it will retry given SDK times out. And in the case where the previous put does succeed, there will be duplicates in the stream. And Firehose delivery doesn't de-dupe the data, so you may want to consider adding de-dupe in your analytical application too.

**Comment by jpilon** [comment]
Great thanks for the explanation. Yes, we added de-dupe checking to the lambda function that processes the firehose output (checks whether file was processed already or not). So far so good.
