### ISSUE TITLE
Diagnosing RecordSendErrors 

### ISSUE THREAD

**Issue by jpilon** [awslabs/amazon-kinesis-agent#71]
Hello,

Everything seems to be running smoothly for us using the Kinesis Agent, however periodically (maybe once or twice a day) we'll get a RecordSendErrors warning in cloudwatch as I have it set to notify us if > 0 errors. 

I'm assuming the agent will retry and resend the failed records automatically and I haven't compared our raw records to the kinesis firehose output yet to see if any are missing, but looking through the agent's log file I don't see any error messages. How does one diagnose this issue or should I just ignore it all together and crank up the cloudwatch threshold?

Any tips / advice?

**Comment by chaochenq** [comment]
Hi,

RecordSendErrors is defined as one unit for each record that returned failure status in in a call to PutRecordBatch, including retries.

Agent uses the PutRecordBatch service API which tries to insert a batch of records at a time. It's not atomic, and each of the records in the batch could fail or succeed independently from the rest, and this is reflected in the response payload of the API call. These are counted a RecordSendErrors. However, when the API call itself fails (other than a throttling failure), then this is counted as a single Service Error, and no record failures are counted in this case. If the API call returned a throttling error, then all records in the batch are considered to have failed (RecordSendErrors is incremented by the batch size). We don't currently make a distinction between throttling and other errors at the record level.

Low rate of partial failures calling Kinesis PutRecords or Firehose PutRecordBatch is expected, and Agent will buffer these failed records and prioritize for retry in the subsequent batch. You can adjust your threshold to be some 0-zero value that reflects your bottom line, and add another monitor on ServiceErrors

**Comment by jpilon** [comment]
Awesome, thanks for the quick reply!
