### ISSUE TITLE
README: Duplicate link

### ISSUE THREAD

**Issue by davidrupp** [awslabs/amazon-kinesis-agent#77]
In the "Getting started" section, item 4, "Using the Amazon Kinesis Agent", the links to "Writing to Amazon Kinesis with Agents" and "Writing to Delivery Streams with Agents" both point to http://docs.aws.amazon.com/kinesis/latest/dev/writing-with-agents.html.

**Comment by witsoej** [comment]
So the first link should probably be:

Writing to Amazon Kinesis Streams Using Amazon Kinesis Agent
http://docs.aws.amazon.com/streams/latest/dev/writing-with-agents.html

And the second link:
Writing to Amazon Kinesis Firehose Using Amazon Kinesis Agent
http://docs.aws.amazon.com/firehose/latest/dev/writing-with-agents.html

**Comment by davidrupp** [comment]
Yeah, I wasn't sure if it was the text or one of the links that was in
error. If someone can confirm, I'd be happy to submit a PR.

**Comment by chaochenq** [comment]
Hmm it works for me though - they seem to be pointing to different links which are correct.

**Comment by davidrupp** [comment]
Yep. Seems okay now. I do see a couple of recent commits that fixed that there was no newline at the end of the file; maybe that was confusing Gollum? Regardless, I will close now. Thanks for reviewing.
