### ISSUE TITLE
LOGTOJSON with Custom Pattern and MatchString Not Working

### ISSUE THREAD

**Issue by neogk666** [awslabs/amazon-kinesis-agent#96]
Being trying to make this Custom log work with Kinesis Agent, and its just not taking in, and the agent keep skipping the long entries. I'm trying to extract only the required fields from apache log. Would this only work with common or combined log format?

Agent file : 

{
  "cloudwatch.emitMetrics": true,
  "cloudwatch.endpoint": "monitoring.us-west-2.amazonaws.com",
  "firehose.endpoint": "firehose.us-west-2.amazonaws.com",

  "flows": [
        {
            "filePattern": "/etc/httpd/logs/access_log",
            "deliveryStream": "wordpress-rs-stream",
            "dataProcessingOptions": [
                {
                    "optionName": "LOGTOJSON",
                    "logFormat": "COMBINEDAPACHELOG",
                    "matchPattern": "^([0-9.]+) (\\d+\/[a-zA-Z]{3}\/\\d+[:]([\\d:]+)\\s[+-]\\d+) (\"(.+?)\") (\"[http]+(.+?)\") (\"[a-z]+\"\\s\"[a-z]+\"\\s\"[a-z]+\"\\s\"[a-z]+\") (\"[A-Z]{2}\"$)",
                    "customFieldNames": ["cip", "datetime", "request", "referer", "device", "country"]
                }
            ]
        }
    ]
}

Apache Custom Log Entry : 

27.32.14.61, 13.54.63.129 172.31.42.43 - - [24/Jun/2017:08:30:05 +0000] "GET / HTTP/1.1" 200 3823 "https://wordpress.domain.com/about/" "Amazon CloudFront" "true" "false" "false" "false" "AU"

And its being skipped with below message : (on agent log)

2017-06-24 12:18:54.869+0000 wordpress.domain.com (FileTailer[fh:wordpress-rs-stream:/etc/httpd/logs/access_log].MetricsEmitter RUNNING) com.amazon.kinesis.streaming.agent.tailing.FileTailer [INFO] FileTailer[fh:wordpress-rs-stream:/etc/httpd/logs/access_log]: Tailer Progress: Tailer has parsed 162 records (4215764 bytes), transformed 0 records, skipped 162 records, and has successfully sent 0 records to destination.
2017-06-24 12:20:16.998+0000 wordpress.domain.com (FileTailer[fh:wordpress-rs-stream:/etc/httpd/logs/access_log]) com.amazon.kinesis.streaming.agent.tailing.FirehoseParser [WARN] 1 record parsed but skipped for processing and delivering

Any help would be appreciated.

**Comment by neogk666** [comment]
The below seems to be parsing on -> https://regex101.com/ perfect..

^([\d:., \d]+)(\S+) (\S+) \[([\w:/]+\s[+\-]\d{4})\] "(.+?)" (\d{3}).* (\d+) "(\S+)" "(\S+).(\S+)" "(\w+)" "(\w+)" "(\w+)" "(\w+)" "(..)"$

However, adding trailing backslash, as in below doesnt work with config file. This time the agent itself wouldn't start up..

Tried this : 
"matchPattern": "^([\\d:., \\d]+)(\\S+) (\\S+) (\\[([\\w:/]+\\s[+\\-]\\d{4})\\]) "(.+?)" (\\d{3}).* (\\d+) "(\\S+)" "(\\S+).(\\S+)" "(\\w+)" "(\\w+)" "(\\w+)" "(\\w+)" "(..)"$"

and this : 

"matchPattern": "^([\\d:., \\d]+)(\\S+) (\\S+) (\\[([\\w:/]+).\\]) "(.+?)" (\\d{3}).* (\\d+) "(\\S+)" "(\\S+).(\\S+)" "(\\w+)" "(\\w+)" "(\\w+)" "(\\w+)" "(..)"$"

in both cases, the agent wont start up - error is => Unexpected character ('(' (code 40)): was expecting comma to separate OBJECT entries

**Comment by chaochenq** [comment]
You will have to escape the double quotes in agent config file, i.e.

`"matchPattern": "^([\\d:., \\d]+)(\\S+) (\\S+) (\\[([\\w:/]+\\s[+\\-]\\d{4})\\]) \"(.+?)\" (\\d{3}).* (\\d+) \"(\\S+)\" \"(\\S+).(\\S+)\" \"(\\w+)\" \"(\\w+)\" \"(\\w+)\" \"(\\w+)\" \"(..)\"$"`

**Comment by neogk666** [comment]
Thanks chaochenq.

It looks like the agent started with the above pattern, however, its not parsing anything. every record being skipped at this moment..

This is the log file : 

`- 172.31.42.43 - - [27/Jun/2017:10:45:26 +0000] "GET /healthcheck.php HTTP/1.1" 200 96 "-" "ELB-HealthChecker/1.0" "-" "-" "-" "-" "-"`

`27.32.14.61, 13.54.63.177 172.31.42.43 - - [27/Jun/2017:10:45:29 +0000] "GET /contact/?_wpcf7_is_ajax_call=1&_wpcf7=4&_wpcf7_request_ver=1498560329207 HTTP/1.1" 200 2 "https://wordpress.niasgk.com/contact/" "Amazon CloudFront" "true" "false" "false" "false" "AU"`

The first line is expected to be skipped; however the second needed to be picked up. 

Any clue?

**Comment by chaochenq** [comment]
Hi, what's the full config? like how many columns are you extracting? It looks like the pattern
`^([\\d:., \\d]+)(\\S+) (\\S+) (\\[([\\w:/]+\\s[+\\-]\\d{4})\\]) \"(.+?)\" (\\d{3}).* (\\d+) \"(\\S+)\" \"(\\S+).(\\S+)\" \"(\\w+)\" \"(\\w+)\" \"(\\w+)\" \"(\\w+)\" \"(..)\"$` parses 16 columns. Do you have 16 columns defined in customFieldNames?

**Comment by neogk666** [comment]
I have 14 columns defined, as below : 

`"customFieldNames": ["cip", "ident", "authuser", "datetime", "request", "code", "size", "referer", "agent", "d1", "d2", "d3", "d4", "country"]`

I was hoping to extract the info as below : 

`"cip" => 27.32.14.61, 13.54.63.177 172.31.42.43 
"ident" => - 
"authuser" => - 
"datetime" => [27/Jun/2017:10:45:29 +0000] 
"request" => "GET /contact/?_wpcf7_is_ajax_call=1&_wpcf7=4&_wpcf7_request_ver=1498560329207 HTTP/1.1" 
"code" => 200 
"size" => 2 
"referer" => "https://wordpress.domain.com/contact/" 
"agent" => "Amazon CloudFront" 
"d1" => "true" 
"d2" => "false" 
"d3" => "false" 
"d4" => "false" 
"country" => "AU"`

**Comment by chaochenq** [comment]
Try this:
`^([\\d:., \\d]+) (\\S+) (\\S+) (\\[[\\w:/]+\\s[+\\-]\\d{4}\\]) \"(.+?)\" (\\d{3}).* (\\d+) \"(\\S+)\" \"(\\S+[^\"]*\\S+)\" \"(\\S+)\" \"(\\w+)\" \"(\\w+)\" \"(\\w+)\" \"(..)\"$`

I was able to get this JSON running against your sample data:

{"cip":"27.32.14.61, 13.54.63.177 172.31.42.43","ident":null,"authuser":null,"datetime":"[27/Jun/2017:10:45:29 +0000]","request":"GET /contact/?_wpcf7_is_ajax_call=1&_wpcf7=4&_wpcf7_request_ver=1498560329207 HTTP/1.1","code":"200","size":"2","referer":"https://wordpress.domain.com/contact/","agent":"Amazon CloudFront","d1":"true","d2":"false","d3":"false","d4":"false","country":"AU"}

**Comment by neogk666** [comment]
Thanks chaochenq. That did worked. Closing this.

**Comment by skumarsinfra** [comment]
Hi, i have same issue, I need some help on below apache logging can you please help me out, I am trying the stream my apache web server logs to kinesis data stream through agent. My agent configuration as below.



{
"cloudwatch.emitMetrics": true,
"kinesis.endpoint": "kinesis.us-east-1.amazonaws.com",
"firehose.endpoint": "firehose.us-east-1.amazonaws.com",
"flows": [
{
  "filePattern": "/opt/httpd-2.4.26/logs/ssl_access_log.*",
  "deliveryStream": "va-qa-app-common-apachelog-delivery",
  "dataProcessingOptions":  [
        {
        "optionName": "LOGTOJSON",
        "logFormat": "COMBINEDAPACHELOG",
        "matchPattern": "^(\S+) (\S+) (\S+) \[([\w:/]+\s[+\-]\d{4})\] "(\S+)\s?(\S+)?\s?(\S+)?" (\d{3}|-) (\d+|-)\s?"?([^"]*)"?\s?"?([^"]*)?"?$"
        "customFieldNames": ["cip", "datetime", "request", "code", "size", "referer", "agent", "d1" ]
        }]
}
]
}

with above config agents starts but he is not able to deliver the logs the kinesis. I tried all combination of regex finally I am approaching you, need some help on this.

My apache log sample below.


96.231.134.120 [04/Aug/2020:23:58:00 +0000] "GET /app/login.do HTTP/1.1" 200 6824 "https://common-app-qa.domain.com/app/esv/invoiceManagement/viewInvoiceDetails.do?invHeaderId=450882&invoiceStatus=PE&navigationSource=DS&navigationURL=https://common-app-qa.domain.com/app/module/invoiceManagement/defaultSearchPage.do" "Mozilla/5.0 (Windows NT 10.0; WOW64; Trident/7.0; rv:11.0) like Gecko" "JSESSIONID=tqV-2ed3xF7eZPYI8piDeQ**.node1; userActiveTime=59; org.springframework.web.servlet.i18n.CookieLocaleResolver.LOCALE=en_US; prevUserActiveTime=59"
